### ISSUE TITLE
Type Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nolde** [doapp-ryanp/serverless-plugin-browserify#14]
Error happening with a mix of functions containing function level package and some without it.

>   Type Error ---------------------------------------------
> 
>      Cannot read property 'length' of undefined
> 
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> 
>   Stack Trace --------------------------------------------
> 
> TypeError: Cannot read property 'length' of undefined
>     at GlobAll.globNext (C:\git\my-module\node_modules\glob-all\glob-all.js:84:20)
>     at GlobAll.run (C:\git\my-module\node_modules\glob-all\glob-all.js:78:8)
>     at Function.globAll.sync (C:\git\my-module\node_modules\glob-all\glob-all.js:192:41)
>     at BbPromise (C:\git\my-module\node_modules\serverless-plugin-browserify\lib\bundle.js:32:31)
>     at SlsBrowserify.bundle (C:\git\my-module\node_modules\serverless-plugin-browserify\lib\bundle.js:31:12)

**Comment by nolde** [comment]
This [pull request](https://github.com/doapp-ryanp/serverless-plugin-browserify/pull/10) should solve this issue.

**Comment by gulbinas** [comment]
got same error
```
Serverless: Writing browserfied bundle to /var/folders/xy/b1189skj16zgcxn2r1s8q8l80000gn/T/addSpecsRecord

  Type Error ---------------------------------------------

  Cannot read property 'length' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'length' of undefined
    at GlobAll.globNext (/Users/aaaa/PyProjects/bc-registry/node_modules/glob-all/glob-all.js:84:20)
```

versions:

```
Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.6.0
     Serverless Version:     1.24.1
```



```
{
  "name": "registry",
  "version": "0.0.0",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "aws-sdk": "^2.6.12",
    "testrpc": "0.0.1",
    "web3": "^0.19.0"
  },
  "devDependencies": {
    "serverless-plugin-browserify": "^1.1.3"
  }
}
```

**Comment by noahsphillips** [comment]
Any progress on this? I am facing the same issue

**Comment by nolde** [comment]
This project appears to have been abandoned.

I recommend trying the fork I made of it: https://github.com/digitalmaas/serverless-plugin-browserifier
