### ISSUE TITLE
file already exists, mkdir '/var/folders...

### ISSUE THREAD

**Issue by tchock** [doapp-ryanp/serverless-plugin-browserify#2]
When trying to use `serverless deploy` with the browserify plugin added I'll get the following error:

```
Error: EEXIST: file already exists, mkdir '/var/folders/4w/_0f5wg2145z8vp3jbq56fzlm0000gn/T/locationCreate'
```

I looked into the *'/var/folders/4w/_0f5wg2145z8vp3jbq56fzlm0000gn/T/* folder during execution and the folders are created when the "Bundling ... with Browserify" output happens. It takes some time and and then the error pops up.

Currently I'm using Serverless **1.2.0**.

Here is the complete output:
```
serverless deploy
Serverless: Bundling locationCreate with Browserify...
Serverless: Bundling locationSendToClient with Browserify...
Serverless: Bundling locationCallback with Browserify...
Serverless: Bundling locationGetFull with Browserify...
Serverless: Bundling locationGetMetadata with Browserify...
Serverless: Bundling locationUpdate with Browserify...
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/var/folders/4w/_0f5wg2145z8vp3jbq56fzlm0000gn/T/locationCreate'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:922:18)
  at b.bundle (/Users/simonjentsch/Documents/.../.../node_modules/serverless-plugin-browserify/lib/bundle.js:39:12)
  at /Users/simonjentsch/Documents/.../.../node_modules/browserify/index.js:779:13
  at ConcatStream.<anonymous> (/Users/simonjentsch/Documents/.../.../node_modules/browserify/node_modules/concat-stream/index.js:36:43)
  at emitNone (events.js:91:20)
  at ConcatStream.emit (events.js:185:7)
  at finishMaybe (/Users/simonjentsch/Documents/.../.../node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
  at endWritable (/Users/simonjentsch/Documents/.../.../node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
  at ConcatStream.Writable.end (/Users/simonjentsch/Documents/.../.../node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
  at Readable.onend (/Users/simonjentsch/Documents/.../.../node_modules/read-only-stream/node_modules/readable-stream/lib/_stream_readable.js:504:10)
  at Readable.g (events.js:291:16)
  at emitNone (events.js:86:13)
  at Readable.emit (events.js:185:7)
  at endReadableNT (/Users/simonjentsch/Documents/.../.../node_modules/read-only-stream/node_modules/readable-stream/lib/_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by amitaymolko** [comment]
+1

**Comment by mzratio** [comment]
+1

**Comment by tomasca** [comment]
+1

**Comment by annieosborne** [comment]
+1
